project_name: devdeck-server

builds:
  - main: .
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

brews:
  - name: devdeck-server
    directory: Formula
    homepage: "https://github.com/devdeck-app/devdeck-server"
    description: "DevDeck server for the DevDeck mobile app"
    license: MIT
    install: |
      bin.install "devdeck-server"
    service: |
      run [opt_bin]/"devdeck-server"
      keep_alive true
    test: |
      require "timeout"
      pid = fork do
        exec "#{bin}/devdeck-server"
      end
      sleep 2
      assert_predicate Process.kill(0, pid), :==, 1
      Process.kill("TERM", pid)
      Process.wait(pid)

changelog:
  use: github
