version: 2
project_name: devdeck-server

builds:
  - main: .
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

brews:
  - name: devdeck-server
    directory: Formula
    homepage: "https://github.com/devdeck-app/devdeck-server"
    commit_author:
      name: Github Actions
      email: actions@github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: devdeck-app
      name: homebrew-devdeck-server
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"
    description: "DevDeck server for the DevDeck mobile app"
    license: MIT
    install: |
      bin.install "devdeck-server"
    service: |
      run [opt_bin]/"devdeck-server"
      keep_alive true
    test: |
      require "timeout"
      pid = fork do
        exec "#{bin}/devdeck-server"
      end
      sleep 2
      assert_predicate Process.kill(0, pid), :==, 1
      Process.kill("TERM", pid)
      Process.wait(pid)

changelog:
  use: github
