name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Verify files
        run: |
          ls -R dist

      - name: Copy Homebrew formula to tap repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://x-access-token:${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/devdeck-app/homebrew-devdeck-server.git
          cp Formula/devdeck-server.rb homebrew-devdeck-server/Formula/devdeck-server.rb
          cd homebrew-devdeck-server
          git add Formula/devdeck-server.rb
          git commit -m "Update formula for ${{ github.ref_name }}"
          git push
